package mcpserver

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/fruitbars/go-xfyun-cli/internal/config"
	"github.com/fruitbars/go-xfyun-cli/internal/ifasr"
	"github.com/fruitbars/go-xfyun-cli/internal/ocr"
	"github.com/fruitbars/go-xfyun-cli/internal/outputfile"
	"github.com/fruitbars/go-xfyun-cli/internal/rtasr"
	"github.com/fruitbars/go-xfyun-cli/internal/tts"
	"github.com/fruitbars/go-xfyun-cli/internal/version"
)

type Service struct {
	credentials config.Credentials
}

func New(credentials config.Credentials) *mcp.Server {
	service := &Service{credentials: credentials}
	server := mcp.NewServer(&mcp.Implementation{
		Name:        "xfyun-ai",
		Title:       "XFYun AI",
		Description: "OCR, speech synthesis, and speech transcription through XFYun large-model APIs",
		Version:     version.Current,
	}, &mcp.ServerOptions{
		Instructions: "XFYun large-model media tools: use xfyun_ocr for document images, xfyun_tts for speech synthesis, xfyun_rtasr for live-style PCM/Opus/Speex streams, and xfyun_ifasr_submit plus xfyun_ifasr_result for completed recordings. Multi-page OCR returns an NDJSON output_path; consume it incrementally instead of loading the entire file. Preserve both IFASR identifiers and poll with wait=false when the host has short tool timeouts. Credentials come from XFYUN_APP_ID, XFYUN_API_KEY, and XFYUN_API_SECRET. File paths are local to this server process. Never overwrite OCR or TTS output unless the user authorized force=true.",
	})

	addOCRTool(server, service)
	addTTSTool(server, service)
	addRTASRTool(server, service)
	addIFASRSubmitTool(server, service)
	addIFASRResultTool(server, service)
	return server
}

type OCRInput struct {
	InputPath       string   `json:"input_path" jsonschema:"Path to a local image or PDF. Unsupported raster formats are converted automatically."`
	OutputPath      string   `json:"output_path,omitempty" jsonschema:"Optional NDJSON destination. Multi-page results use a temporary NDJSON file when omitted."`
	Force           bool     `json:"force,omitempty" jsonschema:"Allow replacement of an existing output_path after all pages succeed."`
	Pages           string   `json:"pages,omitempty" jsonschema:"PDF page selection such as 1-3,5. Default: all pages."`
	PDFDPI          int      `json:"pdf_dpi,omitempty" jsonschema:"PDF page rendering resolution from 72 to 300 DPI. Default: 150."`
	ResultFormat    string   `json:"result_format,omitempty" jsonschema:"json; json,markdown; json,sed; or json,markdown,sed. Default: json,markdown."`
	ResultOption    string   `json:"result_option,omitempty" jsonschema:"normal plus optional char and no_line_position. Default: normal."`
	MarkdownOptions string   `json:"markdown_options,omitempty" jsonschema:"Element controls such as seal=1,qrcode=1,table=2,watermark=0."`
	SEDOptions      string   `json:"sed_options,omitempty" jsonschema:"SED element controls such as seal=1,qrcode=1,table=2,watermark=0."`
	ExifOption      string   `json:"exif_option,omitempty" jsonschema:"Parse EXIF metadata: 0 off or 1 on. Default: 0."`
	AlphaOption     string   `json:"alpha_option,omitempty" jsonschema:"Honor transparent pixels: 0 off or 1 on. Default: 0."`
	RotationAngle   *float64 `json:"rotation_min_angle,omitempty" jsonschema:"Minimum auto-rotation angle from 0 to 180. Default: 5."`
	TimeoutSeconds  int      `json:"timeout_seconds,omitempty" jsonschema:"OCR request timeout per page in seconds. Default: 120."`
}

type OCROutput struct {
	Text          string `json:"text,omitempty"`
	SID           string `json:"sid,omitempty"`
	ResultFormat  string `json:"result_format"`
	PageCount     int    `json:"page_count"`
	OutputPath    string `json:"output_path,omitempty"`
	OutputFormat  string `json:"output_format,omitempty"`
	AutoGenerated bool   `json:"auto_generated,omitempty"`
}

type OCRPageOutput struct {
	Type       string `json:"type"`
	Page       int    `json:"page"`
	Image      int    `json:"image"`
	TotalPages int    `json:"total_pages"`
	DPI        int    `json:"dpi,omitempty"`
	Text       string `json:"text"`
	SID        string `json:"sid,omitempty"`
}

func addOCRTool(server *mcp.Server, service *Service) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "xfyun_ocr",
		Title:       "Recognize an image or PDF",
		Description: "Convert a local raster image or stream a PDF through render, compression, OCR, and release one page at a time. Multi-page results are written incrementally as NDJSON so memory stays bounded.",
		Annotations: annotations(false, true, true),
	}, func(ctx context.Context, req *mcp.CallToolRequest, input OCRInput) (*mcp.CallToolResult, OCROutput, error) {
		if input.InputPath == "" {
			return nil, OCROutput{}, fmt.Errorf("input_path is required")
		}
		if input.ResultFormat == "" {
			input.ResultFormat = "json,markdown"
		}
		if input.ResultOption == "" {
			input.ResultOption = "normal"
		}
		if input.MarkdownOptions == "" {
			input.MarkdownOptions = "watermark=0,page_header=0,page_footer=0,page_number=0,graph=0"
		}
		rotationAngle := 5.0
		if input.RotationAngle != nil {
			rotationAngle = *input.RotationAngle
		}
		client := ocr.Client{Credentials: service.credentials}
		output := OCROutput{ResultFormat: input.ResultFormat}
		var outputFile *os.File
		var outputEncoder *json.Encoder
		var temporaryPath string
		var needsCommit bool
		committed := false
		defer func() {
			if outputFile != nil {
				_ = outputFile.Close()
			}
			if !committed && temporaryPath != "" {
				_ = os.Remove(temporaryPath)
			}
		}()
		openPageSink := func(pageCount int) error {
			if outputFile != nil || (input.OutputPath == "" && pageCount == 1) {
				return nil
			}
			if input.OutputPath != "" {
				absolutePath, tempFile, err := prepareAtomicOutput(input.OutputPath, input.Force)
				if err != nil {
					return err
				}
				output.OutputPath = absolutePath
				outputFile = tempFile
				temporaryPath = tempFile.Name()
				needsCommit = true
			} else {
				tempFile, err := os.CreateTemp("", "xfyun-ocr-*.ndjson")
				if err != nil {
					return fmt.Errorf("create streaming OCR output: %w", err)
				}
				absolutePath, err := filepath.Abs(tempFile.Name())
				if err != nil {
					_ = tempFile.Close()
					_ = os.Remove(tempFile.Name())
					return fmt.Errorf("resolve streaming OCR output: %w", err)
				}
				output.OutputPath = absolutePath
				output.AutoGenerated = true
				outputFile = tempFile
				temporaryPath = tempFile.Name()
			}
			output.OutputFormat = "ndjson"
			outputEncoder = json.NewEncoder(outputFile)
			return nil
		}
		err := ocr.StreamPath(ctx, input.InputPath, input.Pages, input.PDFDPI, func(documentImage ocr.DocumentImage) error {
			if err := openPageSink(documentImage.PageCount); err != nil {
				return err
			}
			requestCtx, cancel := withTimeout(ctx, input.TimeoutSeconds, 120)
			decoded, response, recognizeErr := client.Recognize(requestCtx, documentImage.Data, ocr.Options{
				Encoding: documentImage.Encoding, ResultFormat: input.ResultFormat,
				ResultOption: input.ResultOption, MarkdownElementOption: input.MarkdownOptions,
				SEDElementOption: input.SEDOptions, ExifOption: input.ExifOption, AlphaOption: input.AlphaOption,
				RotationMinAngle: rotationAngle,
			})
			cancel()
			if recognizeErr != nil {
				return fmt.Errorf("OCR page %d image %d: %w", documentImage.Page, documentImage.Index, recognizeErr)
			}
			page := OCRPageOutput{
				Type: "page", Page: documentImage.Page, Image: documentImage.Index,
				TotalPages: documentImage.PageCount, DPI: documentImage.DPI,
				Text: string(decoded), SID: response.Header.SID,
			}
			output.PageCount++
			if outputEncoder != nil {
				if err := outputEncoder.Encode(page); err != nil {
					return fmt.Errorf("write streaming OCR result for page %d: %w", page.Page, err)
				}
			} else {
				output.Text = page.Text
				output.SID = page.SID
			}
			if req != nil && req.Params != nil && req.Session != nil {
				if token := req.Params.GetProgressToken(); token != nil {
					_ = req.Session.NotifyProgress(ctx, &mcp.ProgressNotificationParams{
						ProgressToken: token,
						Progress:      float64(output.PageCount),
						Total:         float64(documentImage.PageCount),
						Message:       fmt.Sprintf("OCR page %d of %d completed", output.PageCount, documentImage.PageCount),
					})
				}
			}
			return nil
		})
		if err != nil {
			return nil, OCROutput{}, err
		}
		if outputFile != nil {
			if err := outputFile.Close(); err != nil {
				return nil, OCROutput{}, fmt.Errorf("close streaming OCR output: %w", err)
			}
			outputFile = nil
			if needsCommit {
				if err := outputfile.Commit(temporaryPath, output.OutputPath, input.Force); err != nil {
					return nil, OCROutput{}, fmt.Errorf("commit OCR output: %w", err)
				}
			}
			committed = true
		}
		return nil, output, nil
	})
}

type TTSInput struct {
	Text              string `json:"text,omitempty" jsonschema:"UTF-8 text up to 64 KiB. Use either text or text_path."`
	TextPath          string `json:"text_path,omitempty" jsonschema:"Local UTF-8 text file. Use either text or text_path."`
	OutputPath        string `json:"output_path" jsonschema:"Local destination path for generated audio."`
	Force             bool   `json:"force,omitempty" jsonschema:"Allow replacement of an existing output file after synthesis succeeds."`
	Voice             string `json:"voice,omitempty" jsonschema:"Enabled XFYun voice ID. Default: x5_lingxiaoxuan_flow."`
	Encoding          string `json:"encoding,omitempty" jsonschema:"Audio encoding such as lame or raw. Default: lame."`
	SampleRate        int    `json:"sample_rate,omitempty" jsonschema:"8000, 16000, or 24000. Default: 24000."`
	Speed             *int   `json:"speed,omitempty" jsonschema:"Speech speed from 0 to 100. Default: 50."`
	Volume            *int   `json:"volume,omitempty" jsonschema:"Volume from 0 to 100. Default: 50."`
	Pitch             *int   `json:"pitch,omitempty" jsonschema:"Pitch from 0 to 100. Default: 50."`
	OralLevel         string `json:"oral_level,omitempty" jsonschema:"low, mid, or high. Official docs limit oral controls to x4 voices. Default: mid."`
	SparkAssist       *int   `json:"spark_assist,omitempty" jsonschema:"Large-model oralization: 0 off or 1 on. Default: 1."`
	StopSplit         *int   `json:"stop_split,omitempty" jsonschema:"Disable server sentence splitting: 0 no or 1 yes. Default: 0."`
	Remain            *int   `json:"remain,omitempty" jsonschema:"Preserve written form: 0 no or 1 yes. Default: 0."`
	BackgroundSound   *int   `json:"background_sound,omitempty" jsonschema:"Background sound: 0 off or 1 on. Default: 0."`
	EnglishReading    *int   `json:"english_reading,omitempty" jsonschema:"English mode: 0 auto/word fallback; 1 letters; 2 auto/letter fallback."`
	NumberReading     *int   `json:"number_reading,omitempty" jsonschema:"Number mode: 0 auto; 1 numeric; 2 digit string; 3 string preferred."`
	ReturnPronounce   *int   `json:"return_pronounce,omitempty" jsonschema:"Return phoneme timing annotation: 0 off or 1 on."`
	VisibleWatermark  *int   `json:"visible_watermark,omitempty" jsonschema:"Audible watermark: 0 off; 1 sentence start; 2 sentence end."`
	ImplicitWatermark bool   `json:"implicit_watermark,omitempty" jsonschema:"Enable an implicit watermark; lame/MP3 only."`
	TimeoutSeconds    int    `json:"timeout_seconds,omitempty" jsonschema:"Request timeout in seconds. Default: 300."`
}

type TTSOutput struct {
	OutputPath    string `json:"output_path"`
	SID           string `json:"sid,omitempty"`
	Encoding      string `json:"encoding"`
	SampleRate    int    `json:"sample_rate"`
	Bytes         int64  `json:"bytes"`
	Pronunciation string `json:"pronunciation,omitempty"`
}

func addTTSTool(server *mcp.Server, service *Service) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "xfyun_tts",
		Title:       "Synthesize speech",
		Description: "Synthesize text with XFYun super smart TTS and atomically write audio to a local output path.",
		Annotations: annotations(false, true, true),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, input TTSInput) (*mcp.CallToolResult, TTSOutput, error) {
		text, err := resolveText(input.Text, input.TextPath)
		if err != nil {
			return nil, TTSOutput{}, err
		}
		if input.OutputPath == "" {
			return nil, TTSOutput{}, fmt.Errorf("output_path is required")
		}
		if input.Voice == "" {
			input.Voice = "x5_lingxiaoxuan_flow"
		}
		if input.Encoding == "" {
			input.Encoding = "lame"
		}
		if input.SampleRate == 0 {
			input.SampleRate = 24000
		}
		speed := 50
		if input.Speed != nil {
			speed = *input.Speed
		}
		volume := 50
		if input.Volume != nil {
			volume = *input.Volume
		}
		pitch := 50
		if input.Pitch != nil {
			pitch = *input.Pitch
		}
		if input.OralLevel == "" {
			input.OralLevel = "mid"
		}
		sparkAssist := intValue(input.SparkAssist, 1)
		absolutePath, tempFile, err := prepareAtomicOutput(input.OutputPath, input.Force)
		if err != nil {
			return nil, TTSOutput{}, err
		}
		tempPath := tempFile.Name()
		committed := false
		defer func() {
			_ = tempFile.Close()
			if !committed {
				_ = os.Remove(tempPath)
			}
		}()
		requestCtx, cancel := withTimeout(ctx, input.TimeoutSeconds, 300)
		defer cancel()
		client := tts.Client{Credentials: service.credentials}
		metadata, err := client.Synthesize(requestCtx, text, tempFile, tts.Options{
			Voice: input.Voice, Encoding: input.Encoding, SampleRate: input.SampleRate,
			Speed: speed, Volume: volume, Pitch: pitch,
			OralLevel: input.OralLevel, SparkAssist: sparkAssist,
			StopSplit: intValue(input.StopSplit, 0), Remain: intValue(input.Remain, 0),
			BackgroundSound: intValue(input.BackgroundSound, 0), EnglishReading: intValue(input.EnglishReading, 0),
			NumberReading: intValue(input.NumberReading, 0), ReturnPronounce: intValue(input.ReturnPronounce, 0),
			VisibleWatermark: intValue(input.VisibleWatermark, 0), ImplicitWatermark: input.ImplicitWatermark,
		})
		if err != nil {
			return nil, TTSOutput{}, err
		}
		if err := tempFile.Close(); err != nil {
			return nil, TTSOutput{}, fmt.Errorf("close temporary audio: %w", err)
		}
		if err := outputfile.Commit(tempPath, absolutePath, input.Force); err != nil {
			return nil, TTSOutput{}, fmt.Errorf("commit audio output: %w", err)
		}
		committed = true
		return nil, TTSOutput{
			OutputPath: absolutePath, SID: metadata.SID, Encoding: metadata.Encoding,
			SampleRate: metadata.SampleRate, Bytes: metadata.Bytes, Pronunciation: metadata.Pronunciation,
		}, nil
	})
}

type RTASRInput struct {
	InputPath          string            `json:"input_path" jsonschema:"Local PCM, Opus, or Speex audio path."`
	Language           string            `json:"language,omitempty" jsonschema:"autodialect or autominor. Default: autodialect."`
	RecognizedLanguage string            `json:"recognized_language,omitempty" jsonschema:"Comma-separated target languages for autominor."`
	AudioEncoding      string            `json:"audio_encoding,omitempty" jsonschema:"pcm_s16le, opus-wb, speex-7, or speex-10. Default: pcm_s16le."`
	SampleRate         int               `json:"sample_rate,omitempty" jsonschema:"PCM sample rate, 8000 or 16000. Default: 16000."`
	RoleType           int               `json:"role_type,omitempty" jsonschema:"Speaker separation: 0 off, 2 on."`
	FeatureIDs         string            `json:"feature_ids,omitempty" jsonschema:"Comma-separated registered voiceprint IDs."`
	Domain             string            `json:"domain,omitempty" jsonschema:"Domain optimization such as finance or medical."`
	SpeakerMatch       bool              `json:"speaker_match,omitempty" jsonschema:"Restrict separated roles to registered feature IDs; requires role_type=2 and feature_ids."`
	KeepPunctuation    *bool             `json:"keep_punctuation,omitempty" jsonschema:"Keep punctuation. Default: true."`
	VADMode            int               `json:"vad_mode,omitempty" jsonschema:"VAD mode: 1 far field or 2 near field. Omit for service default."`
	Extra              map[string]string `json:"extra,omitempty" jsonschema:"Additional documented RTASR query parameters."`
	TimeoutSeconds     int               `json:"timeout_seconds,omitempty" jsonschema:"Overall timeout in seconds. Default: 29100."`
}

type RTASROutput struct {
	Transcript string `json:"transcript"`
	SID        string `json:"sid,omitempty"`
	Segments   int    `json:"segments"`
}

func addRTASRTool(server *mcp.Server, service *Service) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "xfyun_rtasr",
		Title:       "Transcribe audio in real time",
		Description: "Stream a local PCM/Opus/Speex file at real-time pacing and return final transcription text.",
		Annotations: annotations(true, false, true),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, input RTASRInput) (*mcp.CallToolResult, RTASROutput, error) {
		file, err := os.Open(input.InputPath)
		if err != nil {
			return nil, RTASROutput{}, fmt.Errorf("open audio: %w", err)
		}
		defer file.Close()
		if input.Language == "" {
			input.Language = "autodialect"
		}
		if input.AudioEncoding == "" {
			input.AudioEncoding = "pcm_s16le"
		}
		if input.SampleRate == 0 {
			input.SampleRate = 16000
		}
		requestCtx, cancel := withTimeout(ctx, input.TimeoutSeconds, 8*60*60+5*60)
		defer cancel()
		client := rtasr.Client{Credentials: service.credentials}
		result, err := client.Transcribe(requestCtx, file, rtasr.Options{
			Language: input.Language, RecognizedLanguage: input.RecognizedLanguage,
			AudioEncoding: input.AudioEncoding, SampleRate: input.SampleRate,
			RoleType: input.RoleType, FeatureIDs: input.FeatureIDs,
			Domain: input.Domain, SpeakerMatch: input.SpeakerMatch,
			KeepPunctuation: input.KeepPunctuation, VADMode: input.VADMode, Extra: input.Extra,
		}, nil)
		if err != nil {
			return nil, RTASROutput{}, err
		}
		return nil, RTASROutput(result), nil
	})
}

type IFASRSubmitInput struct {
	InputPath        string            `json:"input_path" jsonschema:"Local mp3, wav, pcm, opus, flac, ogg, or speex audio path."`
	Language         string            `json:"language,omitempty" jsonschema:"autodialect or autominor. Default: autodialect."`
	DurationMS       int64             `json:"duration_ms,omitempty" jsonschema:"Exact duration in milliseconds. Zero disables duration checking."`
	Domain           string            `json:"domain,omitempty" jsonschema:"Domain optimization such as finance or medical."`
	RoleType         int               `json:"role_type,omitempty" jsonschema:"Speaker separation: 0 off, 1 generic, 3 voiceprint."`
	RoleNum          int               `json:"role_num,omitempty" jsonschema:"Expected speaker count from 0 to 10."`
	FeatureIDs       string            `json:"feature_ids,omitempty" jsonschema:"Comma-separated registered voiceprint IDs; role_type=3 only; maximum 64."`
	CallbackURL      string            `json:"callback_url,omitempty" jsonschema:"GET callback URL invoked after completion; maximum 512 characters."`
	Smooth           *bool             `json:"smooth,omitempty" jsonschema:"Enable transcript smoothing. Service default: true."`
	Colloquial       *bool             `json:"colloquial,omitempty" jsonschema:"Enable colloquial normalization. Service default: false."`
	VADMode          int               `json:"vad_mode,omitempty" jsonschema:"VAD mode: 1 far field or 2 near field."`
	CantoneseScript  *int              `json:"cantonese_script,omitempty" jsonschema:"Cantonese output: 0 simplified or 1 traditional. Service default: 1."`
	LanguageAnalysis bool              `json:"language_analysis,omitempty" jsonschema:"Enable spoken-language analysis; multilingual entitlement required. Query result_type=analysis or transfer,analysis."`
	Extra            map[string]string `json:"extra,omitempty" jsonschema:"Additional documented upload query parameters."`
}

type IFASRSubmitOutput struct {
	OrderID          string `json:"order_id"`
	SignatureRandom  string `json:"signature_random"`
	TaskEstimateTime int64  `json:"task_estimate_time_ms,omitempty"`
}

func addIFASRSubmitTool(server *mcp.Server, service *Service) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "xfyun_ifasr_submit",
		Title:       "Submit file transcription",
		Description: "Upload a local recording and return identifiers needed to query the asynchronous transcription order.",
		Annotations: annotations(false, false, true),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, input IFASRSubmitInput) (*mcp.CallToolResult, IFASRSubmitOutput, error) {
		file, err := os.Open(input.InputPath)
		if err != nil {
			return nil, IFASRSubmitOutput{}, fmt.Errorf("open audio: %w", err)
		}
		defer file.Close()
		info, err := file.Stat()
		if err != nil {
			return nil, IFASRSubmitOutput{}, fmt.Errorf("stat audio: %w", err)
		}
		client := ifasr.Client{Credentials: service.credentials}
		result, err := client.Transcribe(ctx, file, filepath.Base(input.InputPath), info.Size(), ifasr.Options{
			Language: input.Language, DurationMS: input.DurationMS, Domain: input.Domain,
			CallbackURL: input.CallbackURL, RoleType: input.RoleType, RoleNum: input.RoleNum, FeatureIDs: input.FeatureIDs,
			Smooth: input.Smooth, Colloquial: input.Colloquial, VADMode: input.VADMode,
			CantoneseScript: input.CantoneseScript, Analysis: input.LanguageAnalysis,
			Extra: input.Extra, NoWait: true,
		})
		if err != nil {
			return nil, IFASRSubmitOutput{}, err
		}
		return nil, IFASRSubmitOutput{
			OrderID: result.OrderID, SignatureRandom: result.SignatureRand,
			TaskEstimateTime: result.Response.Content.TaskEstimateTime,
		}, nil
	})
}

type IFASRResultInput struct {
	OrderID         string `json:"order_id" jsonschema:"Order ID returned by xfyun_ifasr_submit."`
	SignatureRandom string `json:"signature_random" jsonschema:"Signature random returned by xfyun_ifasr_submit."`
	ResultType      string `json:"result_type,omitempty" jsonschema:"transfer, analysis, or a comma-separated combination. Default: transfer."`
	Wait            bool   `json:"wait,omitempty" jsonschema:"Wait and poll until the order finishes."`
	PollSeconds     int    `json:"poll_seconds,omitempty" jsonschema:"Polling interval in seconds. Default: 2."`
	MaxWaitSeconds  int    `json:"max_wait_seconds,omitempty" jsonschema:"Maximum wait in seconds. Default: 1800."`
	IncludeRaw      bool   `json:"include_raw,omitempty" jsonschema:"Include the service orderResult JSON string; use for language analysis or fields not represented by transcript."`
}

type IFASRResultOutput struct {
	OrderID            string `json:"order_id"`
	Status             int    `json:"status"`
	FailType           int    `json:"fail_type,omitempty"`
	Transcript         string `json:"transcript,omitempty"`
	OriginalTranscript string `json:"original_transcript,omitempty"`
	RawResult          string `json:"raw_result,omitempty"`
	Language           string `json:"language,omitempty"`
	OriginalDurationMS int64  `json:"original_duration_ms,omitempty"`
}

func addIFASRResultTool(server *mcp.Server, service *Service) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "xfyun_ifasr_result",
		Title:       "Get file transcription result",
		Description: "Query once or wait for an asynchronous recording transcription order and return parsed text/status.",
		Annotations: annotations(true, false, true),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, input IFASRResultInput) (*mcp.CallToolResult, IFASRResultOutput, error) {
		if input.OrderID == "" || input.SignatureRandom == "" {
			return nil, IFASRResultOutput{}, fmt.Errorf("order_id and signature_random are required")
		}
		if input.ResultType == "" {
			input.ResultType = "transfer"
		}
		if input.PollSeconds <= 0 {
			input.PollSeconds = 2
		}
		if input.MaxWaitSeconds <= 0 {
			input.MaxWaitSeconds = 1800
		}
		client := ifasr.Client{Credentials: service.credentials}
		var response ifasr.Response
		var transcript string
		var originalTranscript string
		if input.Wait {
			result, err := client.Wait(ctx, input.OrderID, input.SignatureRandom, ifasr.Options{
				ResultType:   input.ResultType,
				PollInterval: time.Duration(input.PollSeconds) * time.Second,
				MaxWait:      time.Duration(input.MaxWaitSeconds) * time.Second,
			})
			if err != nil {
				return nil, IFASRResultOutput{}, err
			}
			response = result.Response
			transcript = result.Transcript
			originalTranscript = result.OriginalTranscript
		} else {
			var err error
			response, err = client.Query(ctx, input.OrderID, input.SignatureRandom, input.ResultType)
			if err != nil {
				return nil, IFASRResultOutput{}, err
			}
			if response.Content.OrderInfo.Status == 4 {
				transcript, originalTranscript, err = ifasr.ExtractTranscripts(response.Content.OrderResult)
				if err != nil {
					return nil, IFASRResultOutput{}, err
				}
			}
		}
		info := response.Content.OrderInfo
		output := IFASRResultOutput{
			OrderID: input.OrderID, Status: info.Status, FailType: info.FailType,
			Transcript: transcript, OriginalTranscript: originalTranscript, Language: info.Language,
			OriginalDurationMS: info.OriginalDuration,
		}
		if input.IncludeRaw {
			output.RawResult = response.Content.OrderResult
		}
		return nil, output, nil
	})
}

func annotations(readOnly, destructive, openWorld bool) *mcp.ToolAnnotations {
	return &mcp.ToolAnnotations{
		ReadOnlyHint: readOnly, DestructiveHint: boolPointer(destructive),
		OpenWorldHint: boolPointer(openWorld), IdempotentHint: readOnly,
	}
}

func boolPointer(value bool) *bool { return &value }

func intValue(value *int, fallback int) int {
	if value == nil {
		return fallback
	}
	return *value
}

func withTimeout(ctx context.Context, seconds, defaultSeconds int) (context.Context, context.CancelFunc) {
	if seconds <= 0 {
		seconds = defaultSeconds
	}
	return context.WithTimeout(ctx, time.Duration(seconds)*time.Second)
}

func resolveText(text, textPath string) (string, error) {
	if (text == "") == (textPath == "") {
		return "", fmt.Errorf("provide exactly one of text or text_path")
	}
	if text != "" {
		return text, nil
	}
	file, err := os.Open(textPath)
	if err != nil {
		return "", fmt.Errorf("open text file: %w", err)
	}
	defer file.Close()
	data, err := io.ReadAll(io.LimitReader(file, 64*1024+1))
	if err != nil {
		return "", fmt.Errorf("read text file: %w", err)
	}
	if len(data) > 64*1024 {
		return "", fmt.Errorf("text file exceeds the 64 KiB streaming-session limit")
	}
	return string(data), nil
}

func prepareAtomicOutput(outputPath string, force bool) (string, *os.File, error) {
	return outputfile.Prepare(outputPath, force)
}
